project_name: cga
report_sizes: true

before:
  hooks:
    - go mod download
    - go mod tidy
#    - go run github.com/google/wire/cmd/wire@latest
    - go run github.com/securego/gosec/v2/cmd/gosec@latest -quiet ./...
    - go run github.com/go-critic/go-critic/cmd/gocritic@latest check -enableAll ./...
#    - go run github.com/google/osv-scanner/cmd/osv-scanner@latest -r .
    - go test -race ./...

builds:
  -
    id: default
    main: ./cmd/cga/main.go
    env: [ CGO_ENABLED=0 ]
    goos: [ linux, darwin ]
    goarch: [ amd64, arm64 ]

release:
  ids: [ default ]
  draft: true
  replace_existing_draft: true
  target_commitish: "{{ .Commit }}"
  #  discussion_category_name: General
  prerelease: auto
  mode: replace
  header: |
    ## ⚙️ The `{{ .Tag }}` release
  footer: |
    ## Install or update
    
    For native Go installation (any platforms):
    
    ```console
    go install github.com/ghn-toolkit/test-cli/cmd/cga@latest
    ```

    For [Homebrew][brew_url] users (GNU/Linux, macOS):
    
    ```console
    # Tap a new formula:
    brew tap ghn-toolkit/tap
    
    # Installation:
    brew install ghn-toolkit/tap/cli
    
    # Upgrade to the latest:
    brew upgrade ghn-toolkit/tap/cli
    ```
    
    
    ## Your help to improve project
    
    I'd be truly grateful for help with:
    
    - Creating tests (and/or benchmarks) for code.
    - Improving existing functions, structs, or tests.
    - Feature requests with interesting functions that would be good to add.
    
    Your PRs & issues are welcome! Thanks 😉
    
    [brew_url]: https://brew.sh
    [wiki_url]: https://github.com/ghn-toolkit/cli/wiki
  disable: false
  skip_upload: false

brews:
  -
    repository:
      owner: ghn-toolkit
      name: homebrew-tap
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      pull_request:
        enabled: true
    commit_author:
      name: Kent Duong
      email: duonghominhtu1207@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    caveats: |
      After install (or update) cga, let's create a new project via interactive console UI in current folder:
  
      $ cga create
      
      Next, open the generated Ansible inventory file (called hosts.ini) and fill in the variables according to your server configuration. 
      
      And you're ready to automatically deploy this project:
      
      $ cga deploy
      
      That's all you need to know to start! 🎉
    homepage: "https://github.com/ghn-toolkit/cli"
    description: |
      Create a new production-ready project with backend (Golang), frontend (JavaScript, TypeScript) and deploy automation (Ansible, Docker) by running one CLI command.
      Focus on writing code and thinking of business-logic! The CLI will take care of the rest.
    license: Apache 2.0
    skip_upload: false
    dependencies:
      - name: git
      - name: npm

nfpms:
  -
    maintainer: Kent Duong <duonghominhtu1207@gmail.com>
    description: |
      Create a new production-ready project with backend (Golang) by running CLI command.
      Focus on writing code and thinking of business-logic! The CLI will take care of the rest.
    homepage: "https://github.com/ghn-toolkit/cli"
    license: Apache 2.0
    formats: [ deb, rpm, apk, archlinux ]
    dependencies: [ git, npm ]

checksum:
  name_template: "checksums.txt"

changelog:
#  use: github
  sort: asc
  abbrev: -1
  filters:
    exclude: [ "^*.md", "^*.ya?ml" ]
  groups:
    - title: Features
      regexp: ^.*?(F|f)eature.*?$
      order: 0
    - title: Bug fixes
      regexp: ^.*?((B|b)ug)|((F|f)ix).*?$
      order: 1
    - title: Improvements
      regexp: ^.*?(I|i)mprove.*?$
      order: 2
    - title: Updates
      regexp: ^.*?(U|u)pdate.*?$
      order: 3
    - title: Security issues
      regexp: ^.*?(S|s)ecurity.*?$
      order: 4
    - title: Delete unused or stale
      regexp: ^.*?((D|d)elete)|((U|u)nused)|((S|s)tale).*?$
      order: 5
    - title: Others
      order: 999
